// Build data/descriptions.js (for the builder's rules tab) from data/src/descriptions.json.
// Usage (from bellcurve/): node tools/build_desc.mjs
// Fails if a key does not match a library skill or spell, so a typo can't hide a description.
import fs from "node:fs";

const lib = JSON.parse(fs.readFileSync("data/library.json", "utf8"));
const src = JSON.parse(fs.readFileSync("data/src/descriptions.json", "utf8"));
const lc = s => String(s ?? "").toLowerCase();
const keyOf = r => r.spec && !r.spec.startsWith("@") ? `${r.name} (${r.spec})` : r.name;
const known = {
  skills: new Set(lib.skills.flatMap(r => [lc(r.name), lc(keyOf(r))])),
  spells: new Set(lib.spells.map(r => lc(r.name))),
};
let bad = 0;
const out = { skills: {}, spells: {} };
for (const kind of ["skills", "spells"]) for (const [k, v] of Object.entries(src[kind] || {})) {
  if (!known[kind].has(lc(k))) { console.error(`${kind}: "${k}" is not in the library`); bad++; continue; }
  out[kind][lc(k)] = v;
}
if (bad) process.exit(1);
fs.writeFileSync("data/descriptions.js", `/* generated by tools/build_desc.mjs from data/src/descriptions.json; do not edit */\nglobalThis.BC_DESC=${JSON.stringify(out)};\n`);
console.log(`descriptions: ${Object.keys(out.skills).length} skills, ${Object.keys(out.spells).length} spells`);
